[package]
name = "shodo"
version = "0.0.0"
edition = "2024"
rust-version = "1.89.0"
license = "MIT OR Apache-2.0"
description = "Text typesetting library for raikiri (work in progress)"
repository = "https://github.com/fulgur-rs/shodo"
homepage = "https://fulgur.dev/"
readme = "README.md"
keywords = ["typesetting", "text", "layout", "shaping"]
categories = ["text-processing", "graphics"]

[features]
default = ["system-fonts"]
system-fonts = ["fontique/system"]

[dependencies]
fontique = { version = "0.11", default-features = false, features = ["std"] }
skrifa = "0.44"
icu_properties = "2.3"
peniko = "0.6"
unicode-bidi = "0.3.18"
