// Generated field accessors for raikiri pin ab7e619a8f321f03de8b8c8b9342954868e044c8.
// ComputedValues declaration SHA256 a251ea0f4a5c008a7840d55ec674476c87ac1220f4d3cc6440b2a87b2013114a
// S4 style profile source SHA256 4a225616ca97c1b83eeadff6c5228cc23c32ab36a033bb3a4f8d66ecdf4f977f
fn reset_mapped(values: &mut ComputedValues, initial: &ComputedValues) {
    values.font_family = clone_value(&initial.font_family);
    values.color = clone_value(&initial.color);
    values.font_size = clone_value(&initial.font_size);
    values.display = clone_value(&initial.display);
    values.line_height = clone_value(&initial.line_height);
    values.letter_spacing = clone_value(&initial.letter_spacing);
    values.letter_spacing_computed = clone_value(&initial.letter_spacing_computed);
    values.word_spacing = clone_value(&initial.word_spacing);
    values.word_spacing_computed = clone_value(&initial.word_spacing_computed);
    values.white_space = clone_value(&initial.white_space);
    values.white_space_collapse = clone_value(&initial.white_space_collapse);
    values.text_wrap = clone_value(&initial.text_wrap);
    values.font_weight = clone_value(&initial.font_weight);
    values.font_style = clone_value(&initial.font_style);
    values.font_kerning = clone_value(&initial.font_kerning);
    values.font_synthesis = clone_value(&initial.font_synthesis);
    values.font_variant_ligatures = clone_value(&initial.font_variant_ligatures);
    values.font_variant_caps = clone_value(&initial.font_variant_caps);
    values.font_variant_position = clone_value(&initial.font_variant_position);
    values.font_variant_numeric = clone_value(&initial.font_variant_numeric);
    values.font_variant_east_asian = clone_value(&initial.font_variant_east_asian);
    values.font_optical_sizing = clone_value(&initial.font_optical_sizing);
    values.font_variation_settings = clone_value(&initial.font_variation_settings);
    values.text_transform = clone_value(&initial.text_transform);
    values.direction = clone_value(&initial.direction);
    values.unicode_bidi = clone_value(&initial.unicode_bidi);
    values.vertical_align = clone_value(&initial.vertical_align);
    values.text_align = clone_value(&initial.text_align);
    values.text_align_last = clone_value(&initial.text_align_last);
    values.text_justify = clone_value(&initial.text_justify);
    values.text_wrap_style = clone_value(&initial.text_wrap_style);
    values.text_indent = clone_value(&initial.text_indent);
    values.text_indent_ch_factor = clone_value(&initial.text_indent_ch_factor);
    values.text_indent_ch_font = clone_value(&initial.text_indent_ch_font);
    values.text_indent_ch_inherited = clone_value(&initial.text_indent_ch_inherited);
    values.text_indent_hanging = clone_value(&initial.text_indent_hanging);
    values.text_indent_each_line = clone_value(&initial.text_indent_each_line);
    values.orphans = clone_value(&initial.orphans);
    values.widows = clone_value(&initial.widows);
    values.line_break = clone_value(&initial.line_break);
    values.word_break = clone_value(&initial.word_break);
    values.overflow_wrap = clone_value(&initial.overflow_wrap);
    values.hyphens = clone_value(&initial.hyphens);
    values.hyphenate_character = clone_value(&initial.hyphenate_character);
    values.tab_size = clone_value(&initial.tab_size);
    values.text_autospace = clone_value(&initial.text_autospace);
    values.text_spacing_trim = clone_value(&initial.text_spacing_trim);
    values.margin = clone_value(&initial.margin);
    values.padding = clone_value(&initial.padding);
    values.border = clone_value(&initial.border);
}

fn reset_public(values: &mut ComputedValues, initial: &ComputedValues) {
    values.color = clone_value(&initial.color);
    values.background_color = clone_value(&initial.background_color);
    values.font_family = clone_value(&initial.font_family);
    values.font_size = clone_value(&initial.font_size);
    values.font_weight = clone_value(&initial.font_weight);
    values.line_height = clone_value(&initial.line_height);
    values.display = clone_value(&initial.display);
    values.list_style_type = clone_value(&initial.list_style_type);
    values.list_style_position = clone_value(&initial.list_style_position);
    values.list_style_image = clone_value(&initial.list_style_image);
    values.counter_reset = clone_value(&initial.counter_reset);
    values.counter_increment = clone_value(&initial.counter_increment);
    values.counter_set = clone_value(&initial.counter_set);
    values.content = clone_value(&initial.content);
    values.string_set = clone_value(&initial.string_set);
    values.running_templates = clone_value(&initial.running_templates);
    values.position = clone_value(&initial.position);
    values.text_align = clone_value(&initial.text_align);
    values.hanging_punctuation = clone_value(&initial.hanging_punctuation);
    values.text_autospace = clone_value(&initial.text_autospace);
    values.word_space_transform = clone_value(&initial.word_space_transform);
    values.text_spacing_trim = clone_value(&initial.text_spacing_trim);
    values.text_justify = clone_value(&initial.text_justify);
    values.text_align_last = clone_value(&initial.text_align_last);
    values.direction = clone_value(&initial.direction);
    values.writing_mode = clone_value(&initial.writing_mode);
    values.cssom_writing_mode = clone_value(&initial.cssom_writing_mode);
    values.ruby_position = clone_value(&initial.ruby_position);
    values.text_indent = clone_value(&initial.text_indent);
    values.text_indent_ch_factor = clone_value(&initial.text_indent_ch_factor);
    values.text_indent_ch_font = clone_value(&initial.text_indent_ch_font);
    values.text_indent_ch_inherited = clone_value(&initial.text_indent_ch_inherited);
    values.text_indent_hanging = clone_value(&initial.text_indent_hanging);
    values.text_indent_each_line = clone_value(&initial.text_indent_each_line);
    values.padding = clone_value(&initial.padding);
    values.padding_ch = clone_value(&initial.padding_ch);
    values.margin = clone_value(&initial.margin);
    values.margin_ch = clone_value(&initial.margin_ch);
    values.border = clone_value(&initial.border);
    values.border_radius = clone_value(&initial.border_radius);
    values.box_shadow = clone_value(&initial.box_shadow);
    values.outline = clone_value(&initial.outline);
    values.outline_offset = clone_value(&initial.outline_offset);
    values.width = clone_value(&initial.width);
    values.width_ch = clone_value(&initial.width_ch);
    values.height = clone_value(&initial.height);
    values.height_ch = clone_value(&initial.height_ch);
    values.max_width = clone_value(&initial.max_width);
    values.max_height = clone_value(&initial.max_height);
    values.min_width = clone_value(&initial.min_width);
    values.min_height = clone_value(&initial.min_height);
    values.min_block_size = clone_value(&initial.min_block_size);
    values.top = clone_value(&initial.top);
    values.right = clone_value(&initial.right);
    values.bottom = clone_value(&initial.bottom);
    values.left = clone_value(&initial.left);
    values.box_sizing = clone_value(&initial.box_sizing);
    values.overflow = clone_value(&initial.overflow);
    values.text_decoration_line = clone_value(&initial.text_decoration_line);
    values.text_decoration_style = clone_value(&initial.text_decoration_style);
    values.text_decoration_color = clone_value(&initial.text_decoration_color);
    values.text_decoration_thickness = clone_value(&initial.text_decoration_thickness);
    values.text_decoration_skip_ink = clone_value(&initial.text_decoration_skip_ink);
    values.text_decoration_skip_spaces = clone_value(&initial.text_decoration_skip_spaces);
    values.text_decoration_inset = clone_value(&initial.text_decoration_inset);
    values.text_decoration_inset_start_ch = clone_value(&initial.text_decoration_inset_start_ch);
    values.text_decoration_inset_end_ch = clone_value(&initial.text_decoration_inset_end_ch);
    values.text_underline_offset = clone_value(&initial.text_underline_offset);
    values.text_underline_position = clone_value(&initial.text_underline_position);
    values.text_emphasis_position = clone_value(&initial.text_emphasis_position);
    values.text_emphasis_style = clone_value(&initial.text_emphasis_style);
    values.text_emphasis_color = clone_value(&initial.text_emphasis_color);
    values.vertical_align = clone_value(&initial.vertical_align);
    values.font_style = clone_value(&initial.font_style);
    values.font_kerning = clone_value(&initial.font_kerning);
    values.font_optical_sizing = clone_value(&initial.font_optical_sizing);
    values.font_variant_emoji = clone_value(&initial.font_variant_emoji);
    values.font_language_override = clone_value(&initial.font_language_override);
    values.font_variant_ligatures = clone_value(&initial.font_variant_ligatures);
    values.font_synthesis = clone_value(&initial.font_synthesis);
    values.font_variant_position = clone_value(&initial.font_variant_position);
    values.font_palette = clone_value(&initial.font_palette);
    values.font_variant_numeric = clone_value(&initial.font_variant_numeric);
    values.font_variant_east_asian = clone_value(&initial.font_variant_east_asian);
    values.font_variation_settings = clone_value(&initial.font_variation_settings);
    values.font_variant_caps = clone_value(&initial.font_variant_caps);
    values.text_transform = clone_value(&initial.text_transform);
    values.text_combine_upright = clone_value(&initial.text_combine_upright);
    values.text_orientation = clone_value(&initial.text_orientation);
    values.unicode_bidi = clone_value(&initial.unicode_bidi);
    values.visibility = clone_value(&initial.visibility);
    values.z_index = clone_value(&initial.z_index);
    values.word_break = clone_value(&initial.word_break);
    values.line_break = clone_value(&initial.line_break);
    values.overflow_wrap = clone_value(&initial.overflow_wrap);
    values.letter_spacing = clone_value(&initial.letter_spacing);
    values.letter_spacing_computed = clone_value(&initial.letter_spacing_computed);
    values.letter_spacing_ch_factor = clone_value(&initial.letter_spacing_ch_factor);
    values.letter_spacing_ch_font = clone_value(&initial.letter_spacing_ch_font);
    values.word_spacing = clone_value(&initial.word_spacing);
    values.word_spacing_computed = clone_value(&initial.word_spacing_computed);
    values.word_spacing_ch_factor = clone_value(&initial.word_spacing_ch_factor);
    values.word_spacing_ch_font = clone_value(&initial.word_spacing_ch_font);
    values.tab_size = clone_value(&initial.tab_size);
    values.break_before = clone_value(&initial.break_before);
    values.break_after = clone_value(&initial.break_after);
    values.break_inside = clone_value(&initial.break_inside);
    values.float = clone_value(&initial.float);
    values.clear = clone_value(&initial.clear);
    values.white_space = clone_value(&initial.white_space);
    values.white_space_collapse = clone_value(&initial.white_space_collapse);
    values.text_wrap = clone_value(&initial.text_wrap);
    values.text_wrap_style = clone_value(&initial.text_wrap_style);
    values.hyphens = clone_value(&initial.hyphens);
    values.hyphenate_character = clone_value(&initial.hyphenate_character);
    values.hyphenate_limit_chars = clone_value(&initial.hyphenate_limit_chars);
    values.flex_direction = clone_value(&initial.flex_direction);
    values.flex_wrap = clone_value(&initial.flex_wrap);
    values.flex_grow = clone_value(&initial.flex_grow);
    values.flex_shrink = clone_value(&initial.flex_shrink);
    values.flex_basis = clone_value(&initial.flex_basis);
    values.order = clone_value(&initial.order);
    values.justify_content = clone_value(&initial.justify_content);
    values.align_content = clone_value(&initial.align_content);
    values.align_items = clone_value(&initial.align_items);
    values.align_self = clone_value(&initial.align_self);
    values.row_gap = clone_value(&initial.row_gap);
    values.column_gap = clone_value(&initial.column_gap);
    values.quotes = clone_value(&initial.quotes);
    values.quotes_auto = clone_value(&initial.quotes_auto);
    values.text_shadow = clone_value(&initial.text_shadow);
    values.grid_template_columns = clone_value(&initial.grid_template_columns);
    values.grid_template_rows = clone_value(&initial.grid_template_rows);
    values.grid_template_areas = clone_value(&initial.grid_template_areas);
    values.grid_auto_columns = clone_value(&initial.grid_auto_columns);
    values.grid_auto_rows = clone_value(&initial.grid_auto_rows);
    values.grid_auto_flow = clone_value(&initial.grid_auto_flow);
    values.grid_row_start = clone_value(&initial.grid_row_start);
    values.grid_row_end = clone_value(&initial.grid_row_end);
    values.grid_column_start = clone_value(&initial.grid_column_start);
    values.grid_column_end = clone_value(&initial.grid_column_end);
    values.justify_items = clone_value(&initial.justify_items);
    values.justify_self = clone_value(&initial.justify_self);
    values.orphans = clone_value(&initial.orphans);
    values.widows = clone_value(&initial.widows);
    values.background_repeat = clone_value(&initial.background_repeat);
    values.background_attachment = clone_value(&initial.background_attachment);
    values.background_clip = clone_value(&initial.background_clip);
    values.background_origin = clone_value(&initial.background_origin);
    values.background_size = clone_value(&initial.background_size);
    values.background_position = clone_value(&initial.background_position);
    values.background_image = clone_value(&initial.background_image);
    values.object_fit = clone_value(&initial.object_fit);
    values.object_position = clone_value(&initial.object_position);
    values.opacity = clone_value(&initial.opacity);
    values.isolation = clone_value(&initial.isolation);
    values.mix_blend_mode = clone_value(&initial.mix_blend_mode);
    values.mask_image = clone_value(&initial.mask_image);
    values.clip_path = clone_value(&initial.clip_path);
    values.transform = clone_value(&initial.transform);
    values.filter = clone_value(&initial.filter);
    values.table_layout = clone_value(&initial.table_layout);
    values.border_collapse = clone_value(&initial.border_collapse);
    values.border_spacing = clone_value(&initial.border_spacing);
    values.caption_side = clone_value(&initial.caption_side);
    values.empty_cells = clone_value(&initial.empty_cells);
    values.column_count = clone_value(&initial.column_count);
    values.column_width = clone_value(&initial.column_width);
}

pub(crate) fn public_differences(values: &ComputedValues, initial: &ComputedValues) -> Vec<Difference> {
    let mut differences = Vec::new();
    macro_rules! check {
        ($field:ident) => {
            if values.$field != initial.$field {
                differences.push(Difference { field: stringify!($field).into(), value: format!("{:?}", values.$field), initial: format!("{:?}", initial.$field) });
            }
        };
    }
    check!(color);
    check!(background_color);
    check!(font_family);
    check!(font_size);
    check!(font_weight);
    check!(line_height);
    check!(display);
    check!(list_style_type);
    check!(list_style_position);
    check!(list_style_image);
    check!(counter_reset);
    check!(counter_increment);
    check!(counter_set);
    check!(content);
    check!(string_set);
    check!(running_templates);
    check!(position);
    check!(text_align);
    check!(hanging_punctuation);
    check!(text_autospace);
    check!(word_space_transform);
    check!(text_spacing_trim);
    check!(text_justify);
    check!(text_align_last);
    check!(direction);
    check!(writing_mode);
    check!(cssom_writing_mode);
    check!(ruby_position);
    check!(text_indent);
    check!(text_indent_ch_factor);
    check!(text_indent_ch_font);
    check!(text_indent_ch_inherited);
    check!(text_indent_hanging);
    check!(text_indent_each_line);
    check!(padding);
    check!(padding_ch);
    check!(margin);
    check!(margin_ch);
    check!(border);
    check!(border_radius);
    check!(box_shadow);
    check!(outline);
    check!(outline_offset);
    check!(width);
    check!(width_ch);
    check!(height);
    check!(height_ch);
    check!(max_width);
    check!(max_height);
    check!(min_width);
    check!(min_height);
    check!(min_block_size);
    check!(top);
    check!(right);
    check!(bottom);
    check!(left);
    check!(box_sizing);
    check!(overflow);
    check!(text_decoration_line);
    check!(text_decoration_style);
    check!(text_decoration_color);
    check!(text_decoration_thickness);
    check!(text_decoration_skip_ink);
    check!(text_decoration_skip_spaces);
    check!(text_decoration_inset);
    check!(text_decoration_inset_start_ch);
    check!(text_decoration_inset_end_ch);
    check!(text_underline_offset);
    check!(text_underline_position);
    check!(text_emphasis_position);
    check!(text_emphasis_style);
    check!(text_emphasis_color);
    check!(vertical_align);
    check!(font_style);
    check!(font_kerning);
    check!(font_optical_sizing);
    check!(font_variant_emoji);
    check!(font_language_override);
    check!(font_variant_ligatures);
    check!(font_synthesis);
    check!(font_variant_position);
    check!(font_palette);
    check!(font_variant_numeric);
    check!(font_variant_east_asian);
    check!(font_variation_settings);
    check!(font_variant_caps);
    check!(text_transform);
    check!(text_combine_upright);
    check!(text_orientation);
    check!(unicode_bidi);
    check!(visibility);
    check!(z_index);
    check!(word_break);
    check!(line_break);
    check!(overflow_wrap);
    check!(letter_spacing);
    check!(letter_spacing_computed);
    check!(letter_spacing_ch_factor);
    check!(letter_spacing_ch_font);
    check!(word_spacing);
    check!(word_spacing_computed);
    check!(word_spacing_ch_factor);
    check!(word_spacing_ch_font);
    check!(tab_size);
    check!(break_before);
    check!(break_after);
    check!(break_inside);
    check!(float);
    check!(clear);
    check!(white_space);
    check!(white_space_collapse);
    check!(text_wrap);
    check!(text_wrap_style);
    check!(hyphens);
    check!(hyphenate_character);
    check!(hyphenate_limit_chars);
    check!(flex_direction);
    check!(flex_wrap);
    check!(flex_grow);
    check!(flex_shrink);
    check!(flex_basis);
    check!(order);
    check!(justify_content);
    check!(align_content);
    check!(align_items);
    check!(align_self);
    check!(row_gap);
    check!(column_gap);
    check!(quotes);
    check!(quotes_auto);
    check!(text_shadow);
    check!(grid_template_columns);
    check!(grid_template_rows);
    check!(grid_template_areas);
    check!(grid_auto_columns);
    check!(grid_auto_rows);
    check!(grid_auto_flow);
    check!(grid_row_start);
    check!(grid_row_end);
    check!(grid_column_start);
    check!(grid_column_end);
    check!(justify_items);
    check!(justify_self);
    check!(orphans);
    check!(widows);
    check!(background_repeat);
    check!(background_attachment);
    check!(background_clip);
    check!(background_origin);
    check!(background_size);
    check!(background_position);
    check!(background_image);
    check!(object_fit);
    check!(object_position);
    check!(opacity);
    check!(isolation);
    check!(mix_blend_mode);
    check!(mask_image);
    check!(clip_path);
    check!(transform);
    check!(filter);
    check!(table_layout);
    check!(border_collapse);
    check!(border_spacing);
    check!(caption_side);
    check!(empty_cells);
    check!(column_count);
    check!(column_width);
    differences
}

fn reset_measured(values: &mut ComputedValues, initial: &ComputedValues) {
    values.width = clone_value(&initial.width);
    values.height = clone_value(&initial.height);
    values.width_ch = clone_value(&initial.width_ch);
    values.height_ch = clone_value(&initial.height_ch);
    values.min_width = clone_value(&initial.min_width);
    values.max_width = clone_value(&initial.max_width);
    values.min_height = clone_value(&initial.min_height);
    values.max_height = clone_value(&initial.max_height);
    values.min_block_size = clone_value(&initial.min_block_size);
    values.box_sizing = clone_value(&initial.box_sizing);
    values.margin = clone_value(&initial.margin);
    values.border = clone_value(&initial.border);
    values.padding = clone_value(&initial.padding);
    values.margin_ch = clone_value(&initial.margin_ch);
    values.padding_ch = clone_value(&initial.padding_ch);
}

fn reset_atomic(values: &mut ComputedValues, initial: &ComputedValues) {
    values.width = clone_value(&initial.width);
    values.height = clone_value(&initial.height);
    values.box_sizing = clone_value(&initial.box_sizing);
}
